services:
  app:
    build: .
    env_file: .env
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - db

  db:
    image: mysql
    env_file: .env
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
